name: ci-expense-authorization-portal-api

on:
  push:
    branches: [develop, master]
  pull_request:
    types: [opened, reopened, edited, synchronize]
    paths:
      - "expense-authorization/src/API/**"
      - ".github/workflows/ci-expense-authorization-portal-api.yml"

env:
  IMAGE_NAME: expense-authorization-portal-api

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1
        with:
           vs-version: '[16.8)'
      
      - name: Get Source
        uses: actions/checkout@v2

      - name: Build image
        working-directory: expense-authorization/src/API
        run: docker build . --file Dockerfile --tag $IMAGE_NAME
