name: ci-expense-authorization-portal-api

on:
  push:
    branches: [develop, master]
  pull_request:
    types: [opened, reopened, edited, synchronize]
    paths:
      - "expense-authorization/src/API/**"
      - ".github/workflows/ci-expense-authorization-portal-api.yml"

env:
  IMAGE_NAME: expense-authorization-api

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Get Source
        uses: actions/checkout@v2

      - name: Build image
        working-directory: expense-authorization/src/API
        run: docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: Tag the Image in OCP3
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker tag ${{ env.IMAGE_NAME }} ${{ secrets.OPENSHIFT_OCP3_EXTERNAL_REGISTRY }}/${{ secrets.OPENSHIFT_OCP3_TOOLS_NAMESPACE }}/${{ env.IMAGE_NAME }}

      - name: Push frontend to OCP3
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker login ${{ secrets.OPENSHIFT_OCP3_EXTERNAL_REGISTRY }} -u ${{ secrets.OPENSHIFT_OCP3_EXTERNAL_REGISTRY_USER }} -p ${{ secrets.OPENSHIFT_OCP3_EXTERNAL_REGISTRY_PASS }}
          docker image push --all-tags ${{ secrets.OPENSHIFT_OCP3_EXTERNAL_REGISTRY }}/${{ secrets.OPENSHIFT_OCP3_TOOLS_NAMESPACE }}/${{ env.IMAGE_NAME }}
